server:
  port: 8088
spring:
  datasource:
    #mysql
    url: jdbc:mysql://localhost:3306/codex?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #postgresql
#    url: jdbc:postgresql://localhost:5432/datacenter?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false
#    username: root
#    password: 123456
#    driver-class-name: org.postgresql.Driver
